package com.franzliszt.magicmusic.bean.playlist

data class Playlist(
    val action:Any,
    val actionType:Any,
    val adType: Int,
    val anonimous: Boolean,
    val artists: Any,
    val algTags:Any,
    val bookCount:Int,
    val backgroundCoverId: Long,
    val backgroundCoverUrl: Any,
    val cloudTrackCount: Int,
    val bannedTrackIds:Any,
    val commentThreadId: String,
    val copied: Boolean,
    val coverImgId: Long,
    val coverImgId_str: String,
    val coverImgUrl: String,
    val createTime: Long,
    val creator: Creator,
    val commentCount:Long,
    val description: String,
    val englishTitle: Any,
    val highQuality: Boolean,
    val historySharedUsers:Any,
    val gradeStatus:String,
    val id: Long,
    val lastSong:Any,
    val mvResourceInfos:Any,
    val name: String,
    val newImported: Boolean,
    val opRecommend: Boolean,
    val ordered: Boolean,
    val officialTags:Any,
    val officialPlaylistType:Any,
    val playCount: Long,
    val privacy: Int,
    val recommendInfo: Any,
    val recommendText:Any,
    val relateResType:Any,
    val remixVideo:Any,
    val shareStatus: Any,
    val sharedUsers: Any,
    val specialType: Int,
    val status: Int,
    val score:Any,
    val shareCount:Long,
    val subscribed: Boolean,
    val subscribedCount: Long,
    val subscribers: List<Any>,
    val tags: List<String>,
    val titleImage: Long,
    val titleImageUrl: Any,
    val top: Boolean,
    val totalDuration: Int,
    val trackCount: Int,
    val trackIds:Any,
    val trackNumberUpdateTime: Long,
    val trackUpdateTime: Long,
    val tracks: Any,
    val trialMode:Int,
    val updateFrequency: Any,
    val updateTime: Long,
    val userId: Long,
    val videoIds:Any,
    val videos:Any
)