package com.franzliszt.magicmusic.bean.dj

import com.franzliszt.magicmusic.bean.radio.program.Dj

data class DjRadioBean(
    val buyed: Boolean,
    val category: String,
    val categoryId: Int,
    val commentCount: Int,
    val composeVideo: Boolean,
    val createTime: Long,
    val desc: String,
    val discountPrice: Any,
    val dj: Dj,
    val feeScope: Int,
    val finished: Boolean,
    val hightQuality: Boolean,
    val icon: Any,
    val id: Long,
    val intervenePicUrl: String,
    val lastProgramCreateTime: Long,
    val lastProgramId: Long,
    val lastProgramName: Any,
    val likedCount: Int,
    val liveInfo: Any,
    val name: String,
    val originalPrice: Int,
    val picId: Long,
    val picUrl: String,
    val playCount: Long,
    val price: Int,
    val privacy: Boolean,
    val programData:Any,
    val programCount: Int,
    val purchaseCount: Int,
    val radioFeeType: Int,
    val rcmdText: Any,
    val secondCategory: String,
    val secondCategoryId: Int,
    val shareCount: Int,
    val subCount: Int,
    val underShelf: Boolean,
    val videos: Any,
    val whiteList: Boolean
)