package com.franzliszt.magicmusic.bean.song

data class SongUrlBean(
    val br: Int,
    val canExtend: Boolean,
    val channelLayout: Any,
    val code: Int,
    val effectTypes: Any,
    val encodeType: String,
    val expi: Int,
    val fee: Int,
    val flag: Int,
    val freeTimeTrialPrivilege: Any,
    val freeTrialInfo: Any,
    val freeTrialPrivilege: Any,
    val gain: Double,
    val id: Long,
    val level: String,
    val md5: String,
    val payed: Int,
    val peak: Any,
    val podcastCtrp: Any,
    val rightSource: Int,
    val size: Long,
    val time: Long,
    val type: String,
    val uf: Any,
    val url: String,
    val urlSource: Int
)