package com.franzliszt.magicmusic.bean.radio

import com.franzliszt.magicmusic.bean.radio.program.Dj

data class ProgramDetailBean(
    val activityInfo: Any,
    val category: String,
    val categoryId: Int,
    val commentCount: Long,
    val commentDatas: Any,
    val createTime: Long,
    val desc: String,
    val detailRcmdTabOrpheus: String,
    val disableShare: Boolean,
    val dj: Dj,
    val `dynamic`: Boolean,
    val feeInfo: Any,
    val feeScope: Int,
    val icon: Any,
    val id: Int,
    val labelDto: Any,
    val labels: Any,
    val lastProgramCreateTime: Long,
    val lastProgramId: Long,
    val likedCount: Int,
    val limitFreeToast: Any,
    val name: String,
    val original: Boolean,
    val picId: Long,
    val picUrl: String,
    val playCount: Int,
    val privacy: Boolean,
    val programCount: Int,
    val radioFeeType: Int,
    val rcmdText: String,
    val secondCategory: String,
    val secondCategoryId: Int,
    val shareCount: Long,
    val subCount: Long,
    val subed: Boolean,
    val toast: Any,
    val toplistInfo: Any,
    val unlockInfo: Any
)