package com.franzliszt.magicmusic.bean.radio

import com.franzliszt.magicmusic.bean.radio.program.Dj

data class RecommendRadioBean(
    val alg: String,
    val buyed: Boolean,
    val category: String,
    val categoryId: Int,
    val composeVideo: Boolean,
    val copywriter: String,
    val createTime: Long,
    val danmakuCount: Int,
    val desc: String,
    val descPicList: Any,
    val discountPrice: Any,
    val dj: Dj,
    val `dynamic`: Boolean,
    val feeScope: Int,
    val finished: Boolean,
    val hightQuality: Boolean,
    val icon: Any,
    val id: Long,
    val immersionAnimation: Any,
    val immersionCover: Any,
    val intervenePicId: Long,
    val intervenePicUrl: String,
    val lastProgramCreateTime: Long,
    val lastProgramId: Long,
    val lastProgramName: String,
    val lastUpdateProgramName: String,
    val liveInfo: Any,
    val manualTagsDTO: Any,
    val name: String,
    val original: String,
    val originalPrice: Int,
    val picId: Long,
    val picUrl: String,
    val playCount: Long,
    val price: Int,
    val privacy: Boolean,
    val programCount: Int,
    val purchaseCount: Int,
    val radioFeeType: Int,
    val rcmdText: String,
    val rcmdtext: String,
    val replaceResource: Any,
    val scoreInfoDTO: Any,
    val secondCategory: String,
    val secondCategoryId: Int,
    val shortName: Any,
    val subCount: Int,
    val subed: Boolean,
    val taskId: Int,
    val underShelf: Boolean,
    val videos: Any,
    val whiteList: Boolean
)