package com.franzliszt.magicmusic.bean.user

data class UserProfileBean(
    val accountStatus: Int,
    val accountType:Int,
    val alg: String,
    val anchor: Boolean,
    val authStatus: Int,
    val authenticationTypes: Int,
    val authority: Int,
    val avatarDetail: Any,
    val avatarImgId: Long,
    val avatarImgIdStr: String,
    val avatarImgId_str: String,
    val avatarUrl: String,
    val allSubscribedCount:Int,
    val artistIdentity:Any,
    val authenticated:Boolean,
    val backgroundImgId: Long,
    val backgroundImgIdStr: String,
    val backgroundUrl: String,
    val birthday: Long,
    val blacklist:Boolean,
    val city: Int,
    val createTime:Long,
    val cCount:Int,
    val defaultAvatar: Boolean,
    val description: String,
    val detailDescription: String,
    val djStatus: Int,
    val expertTags: Any,
    val experts: Any,
    val eventCount:Int,
    val followed: Boolean,
    val followeds: Int,
    val follows: Int,
    val followTime:Any,
    val followMe:Boolean,
    val gender: Int,
    val inBlacklist:Boolean,
    val isAnchor:Boolean,
    val locationStatus:Int,
    val lastLoginIP:String,
    val lastLoginTime:Long,
    val mutual: Boolean,
    val nickname: String,
    val newFollows:Int,
    val playlistBeSubscribedCount: Int,
    val playlistCount: Int,
    val privacyItemUnlimit:Any,
    val province: Int,
    val remarkName: Any,
    val shortUserName:String,
    val signature: String,
    val sDJPCount:Int,
    val sCount:Int,
    val userName:String,
    val userId: Long,
    val userType: Int,
    val vipType: Int,

)